### ISSUE TITLE
Transactions Entered in the Wrong Column

### ISSUE THREAD

**Issue by anthonylavado** [aspirebudgetingmobile/aspirebudgeting_ios#161]
When entering a new transaction from the app, it gets inserted with the date starting in the Status column, and continuing into the columns beside that:
![2022-02-02 13_34_58-Lavado Budget v3 3 - Google Sheets — Mozilla Firefox](https://user-images.githubusercontent.com/596194/152216862-f1c35339-4ecb-453b-9f11-caadc731f37e.png)

If I manually enter a transaction on the web, that is displayed correctly in the app.

Using sheet version 3.3, with App Store release 2.0.1.1, on iOS 15.3.

**Comment by anthonylavado** [comment]
Tested against a blank sheet and I don't see the issue. Since this was a simple sheet for starting, I'll retrace my steps and see where it goes wrong. Either way, issue closed for now.

**Comment by PMilstone** [comment]
Is there a way to resolve this issue without creating an entirely new sheet? I have been experiencing this for some time now which has made me stop using the app.
